name: on push to main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: heroku login
        run: heroku container:login
      - name: Build and push Docker image
        run: heroku container:push web --app $HEROKU_APP_NAME

  release:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: heroku login
        run: heroku container:login
      - name: release Docker image
        run: heroku container:release web --app $HEROKU_APP_NAME
